import type {
  ArbitrageOpportunity,
  Trade,
  BotStats,
  PnlDataPoint,
  BotSettings,
} from "@/types";

export const mockStats: BotStats = {
  status: "running",
  uptimeSeconds: 14523,
  totalPnlToday: 4812.5,
  totalPnlAllTime: 187340.0,
  tradesTotal: 342,
  tradesWon: 289,
  tradesLost: 53,
  openPositions: 3,
  opportunitiesScanned: 1847,
  lastScanAt: new Date(Date.now() - 8000).toISOString(),
};

export const mockOpportunities: ArbitrageOpportunity[] = [
  {
    id: "opp-001",
    type: "inter-grade",
    buyGrade: "WTI",
    buyExchange: "NYMEX",
    buyPrice: 82.14,
    sellGrade: "Brent",
    sellExchange: "ICE",
    sellPrice: 84.22,
    spread: 2.08,
    profitPct: 2.53,
    estimatedProfit: 2080,
    volume: 1000,
    expiresInSeconds: 47,
    detectedAt: new Date(Date.now() - 12000).toISOString(),
  },
  {
    id: "opp-002",
    type: "inter-exchange",
    buyGrade: "Brent",
    buyExchange: "CME",
    buyPrice: 84.05,
    sellGrade: "Brent",
    sellExchange: "ICE",
    sellPrice: 84.41,
    spread: 0.36,
    profitPct: 0.43,
    estimatedProfit: 360,
    volume: 1000,
    expiresInSeconds: 22,
    detectedAt: new Date(Date.now() - 5000).toISOString(),
  },
  {
    id: "opp-003",
    type: "inter-grade",
    buyGrade: "Mars",
    buyExchange: "NYMEX",
    buyPrice: 79.88,
    sellGrade: "WTI",
    sellExchange: "NYMEX",
    sellPrice: 82.14,
    spread: 2.26,
    profitPct: 2.83,
    estimatedProfit: 2260,
    volume: 1000,
    expiresInSeconds: 91,
    detectedAt: new Date(Date.now() - 3000).toISOString(),
  },
  {
    id: "opp-004",
    type: "time-spread",
    buyGrade: "WTI",
    buyExchange: "NYMEX",
    buyPrice: 82.14,
    sellGrade: "WTI",
    sellExchange: "NYMEX",
    sellPrice: 83.02,
    spread: 0.88,
    profitPct: 1.07,
    estimatedProfit: 880,
    volume: 1000,
    expiresInSeconds: 134,
    detectedAt: new Date(Date.now() - 30000).toISOString(),
  },
  {
    id: "opp-005",
    type: "inter-grade",
    buyGrade: "Dubai",
    buyExchange: "DME",
    buyPrice: 81.3,
    sellGrade: "Brent",
    sellExchange: "ICE",
    sellPrice: 84.22,
    spread: 2.92,
    profitPct: 3.59,
    estimatedProfit: 2920,
    volume: 1000,
    expiresInSeconds: 58,
    detectedAt: new Date(Date.now() - 7000).toISOString(),
  },
];

export const mockTrades: Trade[] = [
  {
    id: "trd-001",
    opportunityId: "opp-hist-001",
    type: "inter-grade",
    buyGrade: "WTI",
    buyExchange: "NYMEX",
    buyPrice: 81.9,
    sellGrade: "Brent",
    sellExchange: "ICE",
    sellPrice: 84.1,
    volume: 1000,
    grossProfit: 2200,
    fees: 145,
    netProfit: 2055,
    status: "closed",
    openedAt: new Date(Date.now() - 3600000).toISOString(),
    closedAt: new Date(Date.now() - 3540000).toISOString(),
  },
  {
    id: "trd-002",
    opportunityId: "opp-hist-002",
    type: "inter-exchange",
    buyGrade: "Brent",
    buyExchange: "CME",
    buyPrice: 84.0,
    sellGrade: "Brent",
    sellExchange: "ICE",
    sellPrice: 84.38,
    volume: 1000,
    grossProfit: 380,
    fees: 120,
    netProfit: 260,
    status: "closed",
    openedAt: new Date(Date.now() - 7200000).toISOString(),
    closedAt: new Date(Date.now() - 7155000).toISOString(),
  },
  {
    id: "trd-003",
    opportunityId: "opp-hist-003",
    type: "inter-grade",
    buyGrade: "Mars",
    buyExchange: "NYMEX",
    buyPrice: 80.1,
    sellGrade: "WTI",
    sellExchange: "NYMEX",
    sellPrice: 82.05,
    volume: 1000,
    grossProfit: 1950,
    fees: 145,
    netProfit: 1805,
    status: "closed",
    openedAt: new Date(Date.now() - 10800000).toISOString(),
    closedAt: new Date(Date.now() - 10740000).toISOString(),
  },
  {
    id: "trd-004",
    opportunityId: "opp-hist-004",
    type: "time-spread",
    buyGrade: "WTI",
    buyExchange: "NYMEX",
    buyPrice: 82.5,
    sellGrade: "WTI",
    sellExchange: "NYMEX",
    sellPrice: 82.8,
    volume: 1000,
    grossProfit: 300,
    fees: 130,
    netProfit: 170,
    status: "open",
    openedAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "trd-005",
    opportunityId: "opp-hist-005",
    type: "inter-grade",
    buyGrade: "Dubai",
    buyExchange: "DME",
    buyPrice: 81.0,
    sellGrade: "Brent",
    sellExchange: "ICE",
    sellPrice: 84.1,
    volume: 1000,
    grossProfit: 3100,
    fees: 160,
    netProfit: 2940,
    status: "open",
    openedAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: "trd-006",
    opportunityId: "opp-hist-006",
    type: "inter-exchange",
    buyGrade: "WTI",
    buyExchange: "CME",
    buyPrice: 82.2,
    sellGrade: "WTI",
    sellExchange: "NYMEX",
    sellPrice: 82.18,
    volume: 500,
    grossProfit: -10,
    fees: 110,
    netProfit: -120,
    status: "closed",
    openedAt: new Date(Date.now() - 14400000).toISOString(),
    closedAt: new Date(Date.now() - 14340000).toISOString(),
  },
];

export const mockPnlHistory: PnlDataPoint[] = Array.from({ length: 24 }, (_, i) => {
  const base = i * 200;
  const noise = Math.random() * 400 - 100;
  return {
    timestamp: new Date(Date.now() - (23 - i) * 3600000).toISOString(),
    pnl: Math.max(-200, base + noise - (i > 0 ? (i - 1) * 200 + noise : 0)),
    cumPnl: Math.max(0, base + noise),
  };
});

export const mockSettings: BotSettings = {
  minProfitPct: 0.3,
  maxPositionSizeBarrels: 5000,
  maxOpenPositions: 5,
  scanIntervalSeconds: 5,
  enabledExchanges: ["NYMEX", "ICE", "CME", "DME"],
  enabledGrades: ["WTI", "Brent", "Dubai", "Mars"],
  autoTrade: false,
};
